/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.conductor.conductorproject.order.api;

import com.conductor.conductorproject.order.model.CompleOrder;
import com.conductor.conductorproject.order.model.Orders;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.*;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-03-26T11:41:11.692309-03:00[America/Sao_Paulo]")
@Api(value = "Order", description = "the Order API")
@RequestMapping(value = "/conductor/api/v1")
public interface OrderApi {

    @ApiOperation(value = "Return a order by parameters", nickname = "getOrder", notes = "Return an order by asomething parameters sent in the request", response = Orders.class, tags={ "Order", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Operation successful", response = Orders.class),
        @ApiResponse(code = 400, message = "Bad Request"),
        @ApiResponse(code = 404, message = "Not Found"),
        @ApiResponse(code = 500, message = "Internal Error") })
    @RequestMapping(value = "/Order",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Orders> getOrder(@NotNull @ApiParam(value = "Order ID to retrieve an order", required = true)
                                    @Valid @RequestParam(value = "orderId", required = true) Long orderId
);


    @ApiOperation(value = "Generate a new Order", nickname = "postOrder", notes = "Generate a new order composed by order id, address, confirmation date, status order items and total", response = Orders.class, tags={ "Order", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Order create sucessful", response = Orders.class),
        @ApiResponse(code = 400, message = "Bad Request"),
        @ApiResponse(code = 404, message = "Not Found"),
        @ApiResponse(code = 500, message = "Internal Error") })
    @RequestMapping(value = "/Order",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> postOrder(@ApiParam(value = "Input data to create a new order" ,required=true )  @Valid @RequestBody CompleOrder body
);

}
