/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.conductor.conductorproject.api;

import com.conductor.conductorproject.models.Order;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-03-25T17:39:41.818893-03:00[America/Sao_Paulo]")
@Api(value = "Order", description = "the Order API")
public interface OrderApi {

    @ApiOperation(value = "Return a order by parameters", nickname = "getOrder", notes = "Return an order by asomething parameters sent in the request", response = Order.class, tags={ "Order", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Operation successful", response = Order.class),
        @ApiResponse(code = 400, message = "Bad Request"),
        @ApiResponse(code = 404, message = "Not Found"),
        @ApiResponse(code = 500, message = "Internal Error") })
    @RequestMapping(value = "/Order",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<Order> getOrder(@ApiParam(value = "Input data to retrieve a store" ,required=true )  @Valid @RequestBody Order body
);


    @ApiOperation(value = "Generate a new Order", nickname = "postOrder", notes = "Generate a new order composed by order id, address, confirmation date, status order items and total", response = Order.class, tags={ "Order", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Order create sucessful", response = Order.class),
        @ApiResponse(code = 400, message = "Bad Request"),
        @ApiResponse(code = 404, message = "Not Found"),
        @ApiResponse(code = 500, message = "Internal Error") })
    @RequestMapping(value = "/Order",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Order> postOrder(@ApiParam(value = "Input data to create a new order" ,required=true )  @Valid @RequestBody Order body
);

}
