/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.conductor.conductorproject.api;

import com.conductor.conductorproject.models.Payment;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-03-25T17:39:41.818893-03:00[America/Sao_Paulo]")
@Api(value = "Payment", description = "the Payment API")
public interface PaymentApi {

    @ApiOperation(value = "Generate a payment for an order", nickname = "paymentPost", notes = "Generate a payment for an order, composed by status, credit card number and payment date", tags={ "Payment", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Payment sucessful"),
        @ApiResponse(code = 400, message = "Bad Request"),
        @ApiResponse(code = 404, message = "Not Found"),
        @ApiResponse(code = 500, message = "Internal Error") })
    @RequestMapping(value = "/Payment",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> paymentPost(@ApiParam(value = "Input data to create a new Payment for an order" ,required=true )  @Valid @RequestBody Payment body
,@NotNull @ApiParam(value = "The order identifier for payment", required = true) @Valid @RequestParam(value = "orderId", required = true) String orderId
);

}
